export const PERMISSIONS = [
  ['dashboard.view', 'Ver resumen', 'General'],
  ['search.use', 'Usar búsqueda global', 'General'],
  ['customers.view', 'Ver clientes', 'Clientes'],
  ['customers.create', 'Crear clientes', 'Clientes'],
  ['customers.update', 'Editar clientes', 'Clientes'],
  ['customers.delete', 'Eliminar clientes', 'Clientes'],
  ['customers.export', 'Exportar clientes', 'Clientes'],
  ['vehicles.view', 'Ver vehículos', 'Vehículos'],
  ['vehicles.create', 'Crear vehículos', 'Vehículos'],
  ['vehicles.update', 'Editar vehículos', 'Vehículos'],
  ['vehicles.export', 'Exportar vehículos', 'Vehículos'],
  ['orders.view', 'Ver órdenes', 'Órdenes'],
  ['orders.create', 'Recibir vehículos', 'Órdenes'],
  ['orders.inspect', 'Realizar inspecciones', 'Órdenes'],
  ['orders.diagnose', 'Registrar diagnósticos', 'Órdenes'],
  ['orders.estimate', 'Preparar presupuestos', 'Órdenes'],
  ['orders.approve', 'Registrar autorizaciones', 'Órdenes'],
  ['orders.no_charge', 'Autorizar trabajos sin cargo', 'Órdenes'],
  ['orders.assign', 'Asignar técnicos', 'Órdenes'],
  ['orders.execute', 'Ejecutar trabajos', 'Órdenes'],
  ['orders.quality', 'Control de calidad', 'Órdenes'],
  ['orders.deliver', 'Entregar vehículos', 'Órdenes'],
  ['orders.cancel', 'Anular órdenes', 'Órdenes'],
  ['orders.print', 'Imprimir presupuestos y entregas', 'Órdenes'],
  ['inventory.view', 'Ver inventario', 'Inventario'],
  ['inventory.cost', 'Consultar costos', 'Inventario'],
  ['inventory.adjust', 'Ajustar inventario', 'Inventario'],
  ['inventory.consume', 'Utilizar repuestos', 'Inventario'],
  ['inventory.request', 'Solicitar repuestos', 'Inventario'],
  ['purchases.manage', 'Gestionar compras', 'Inventario'],
  ['purchases.cancel', 'Cancelar compras y solicitudes pendientes', 'Inventario'],
  ['purchases.pay', 'Pagar a proveedores', 'Finanzas'],
  ['purchases.reverse', 'Revertir registros de pago a proveedores', 'Finanzas'],
  ['billing.view', 'Ver facturación y caja', 'Finanzas'],
  ['billing.invoice', 'Facturar', 'Finanzas'],
  ['billing.collect', 'Cobrar', 'Finanzas'],
  ['cash.manage', 'Registrar gastos y otros ingresos', 'Finanzas'],
  ['billing.void', 'Anular comprobantes', 'Finanzas'],
  ['billing.reverse', 'Revertir registros de cobro', 'Finanzas'],
  ['billing.cost', 'Consultar costos y utilidad', 'Finanzas'],
  ['billing.export', 'Exportar finanzas', 'Finanzas'],
  ['billing.print', 'Imprimir comprobantes', 'Finanzas'],
  ['reports.view', 'Ver reportes', 'Reportes'],
  ['reports.export', 'Exportar reportes', 'Reportes'],
  ['employees.manage', 'Administrar usuarios y roles', 'Administración'],
  ['branches.manage', 'Administrar sucursales', 'Administración'],
  ['settings.manage', 'Configurar taller', 'Administración'],
  ['documents.view', 'Ver documentos', 'Administración'],
  ['documents.upload', 'Subir documentos', 'Administración'],
  ['documents.delete', 'Eliminar documentos', 'Administración'],
  ['documents.manage', 'Administrar todos los documentos', 'Administración'],
  ['support.manage', 'Gestionar soporte', 'Administración'],
];
export const MANAGER_PERMISSIONS = PERMISSIONS.map(([code]) => code).filter(
  (code) =>
    ![
      'billing.void',
      'billing.reverse',
      'purchases.reverse',
      'purchases.cancel',
      'customers.delete',
      'orders.no_charge',
    ].includes(code),
);
export const TECHNICIAN_PERMISSIONS = [
  'dashboard.view',
  'search.use',
  'customers.view',
  'vehicles.view',
  'orders.view',
  'orders.inspect',
  'orders.diagnose',
  'orders.execute',
  'inventory.view',
  'inventory.consume',
  'inventory.request',
  'documents.view',
  'documents.upload',
];
export const RECEPTION_PERMISSIONS = [
  'dashboard.view',
  'search.use',
  'customers.view',
  'customers.create',
  'customers.update',
  'vehicles.view',
  'vehicles.create',
  'vehicles.update',
  'orders.view',
  'orders.create',
  'orders.estimate',
  'orders.approve',
  'orders.deliver',
  'orders.print',
  'billing.view',
  'billing.collect',
  'documents.view',
  'documents.upload',
];
export const CASHIER_PERMISSIONS = [
  'dashboard.view',
  'search.use',
  'customers.view',
  'vehicles.view',
  'orders.view',
  'billing.view',
  'billing.invoice',
  'billing.print',
  'billing.collect',
  'billing.export',
  'purchases.pay',
];
export const INVENTORY_PERMISSIONS = [
  'dashboard.view',
  'search.use',
  'orders.view',
  'inventory.view',
  'inventory.cost',
  'inventory.adjust',
  'inventory.consume',
  'purchases.manage',
  'inventory.request',
  'reports.view',
];
