export const PERMISSIONS=[
  ['dashboard.view','Ver resumen','General'],['search.use','Usar búsqueda global','General'],
  ['customers.view','Ver clientes','Clientes'],['customers.create','Crear clientes','Clientes'],['customers.update','Editar clientes','Clientes'],['customers.delete','Eliminar clientes','Clientes'],['customers.export','Exportar clientes','Clientes'],
  ['vehicles.view','Ver vehículos','Vehículos'],['vehicles.create','Crear vehículos','Vehículos'],['vehicles.update','Editar vehículos','Vehículos'],['vehicles.export','Exportar vehículos','Vehículos'],
  ['orders.view','Ver órdenes','Órdenes'],['orders.create','Recibir vehículos','Órdenes'],['orders.inspect','Realizar inspecciones','Órdenes'],['orders.diagnose','Registrar diagnósticos','Órdenes'],['orders.estimate','Preparar presupuestos','Órdenes'],['orders.approve','Registrar autorizaciones','Órdenes'],['orders.assign','Asignar técnicos','Órdenes'],['orders.execute','Ejecutar trabajos','Órdenes'],['orders.quality','Control de calidad','Órdenes'],['orders.deliver','Entregar vehículos','Órdenes'],['orders.cancel','Anular órdenes','Órdenes'],
  ['inventory.view','Ver inventario','Inventario'],['inventory.cost','Consultar costos','Inventario'],['inventory.adjust','Ajustar inventario','Inventario'],['inventory.consume','Utilizar repuestos','Inventario'],['purchases.manage','Gestionar compras','Inventario'],
  ['billing.view','Ver facturación y caja','Finanzas'],['billing.invoice','Facturar','Finanzas'],['billing.collect','Cobrar','Finanzas'],['cash.manage','Registrar gastos y otros ingresos','Finanzas'],['billing.void','Anular comprobantes','Finanzas'],['billing.cost','Consultar costos y utilidad','Finanzas'],['billing.export','Exportar finanzas','Finanzas'],
  ['reports.view','Ver reportes','Reportes'],['reports.export','Exportar reportes','Reportes'],
  ['employees.manage','Administrar usuarios y roles','Administración'],['branches.manage','Administrar sucursales','Administración'],['settings.manage','Configurar taller','Administración'],['documents.manage','Administrar documentos','Administración'],['support.manage','Gestionar soporte','Administración']
];
export const MANAGER_PERMISSIONS=PERMISSIONS.map(([code])=>code).filter(code=>!['billing.void','customers.delete'].includes(code));
export const TECHNICIAN_PERMISSIONS=['dashboard.view','search.use','customers.view','vehicles.view','orders.view','orders.inspect','orders.diagnose','orders.execute','inventory.view','inventory.consume','documents.manage'];
export const RECEPTION_PERMISSIONS=['dashboard.view','search.use','customers.view','customers.create','customers.update','vehicles.view','vehicles.create','vehicles.update','orders.view','orders.create','orders.estimate','orders.approve','orders.deliver','billing.view','billing.collect','documents.manage'];
export const CASHIER_PERMISSIONS=['dashboard.view','search.use','customers.view','vehicles.view','orders.view','billing.view','billing.invoice','billing.collect','billing.export'];
export const INVENTORY_PERMISSIONS=['dashboard.view','search.use','orders.view','inventory.view','inventory.cost','inventory.adjust','inventory.consume','purchases.manage','reports.view'];
